spring.application.name=Registration
server.port=9090

#server.address=  10.80.241.94
#server.error.include-message=always
#server.error.include-binding-errors=always
#server.error.include-stacktrace=always

spring.mvc.view.prefix=WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/
management.endpoints.web.exposure.include=health

spring.datasource.url = jdbc:postgresql://localhost:5432/Registration_Form
spring.datasource.username=postgres
spring.datasource.password=1515
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql = true
spring.jpa.format-sql =true

server.forward-headers-strategy=framework
server.servlet.session.timeout=30m

# SMTP  Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=11229a048@kanchiuniv.ac.in
spring.mail.password=avvobfpsasznpvvm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# GitHub OAuth2 configuration
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23lij3JP61rKEAyS7C}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:99497e6f9d10b6d2e6c5e57f2904c0a0ceb500e1}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Emudhra OIDC configuration
spring.security.oauth2.client.registration.emudhra.client-id=${EMUDHRA_CLIENT_ID:15694933516c5a4ac2-411c-4f8b-ad84-6d3fca27c3bf}
spring.security.oauth2.client.registration.emudhra.client-secret=${EMUDHRA_CLIENT_SECRET:-dw_6EWUDUeCx_erISe_m977HUngEXbkEHP-rV8ErJg}
spring.security.oauth2.client.registration.emudhra.scope=profile,email
spring.security.oauth2.client.registration.emudhra.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.emudhra.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.emudhra.authorization-uri=https://qa.securepass.me/AuthPage/oauth/authorize/1
spring.security.oauth2.client.provider.emudhra.token-uri=https://qa.securepass.me/AuthPage/oauth/token/1
spring.security.oauth2.client.provider.emudhra.jwk-set-uri=https://qa.securepass.me/AuthPage/oauth/jwks
spring.security.oauth2.client.provider.emudhra.user-info-uri=https://qa.securepass.me/AuthPage/userinfo
app.security.oauth2.emudhra.expected-issuer=${EMUDHRA_EXPECTED_ISSUER:https://qa.securepass.me}

# Emudhra SAML configuration
#spring.security.saml2.relyingparty.registration.emudhra.entity-id={baseUrl}/saml2/service-provider-metadata/{registrationId}
spring.security.saml2.relyingparty.registration.emudhra.assertingparty.metadata-uri=https://demo.securepass.me/SPAuthPage/saml/metadata
#spring.security.saml2.relyingparty.registration.emudhra.assertingparty.singlesignon.url=https://demo.securepass.me/SPAuthPage/saml2/sso/1
#spring.security.saml2.relyingparty.registration.emudhra.assertingparty.singlesignon.binding=POST
#spring.security.saml2.relyingparty.rfegistration.emudhra.assertingparty.want-authn-requests-signed=false
#spring.security.saml2.relyingparty.registration.emudhra.assertingparty.verification.credentials[0].certificate-location=classpath:emudhra.crt
spring.security.saml2.relyingparty.registration.emudhra.identityprovider.entity-id=https://demo.securepass.me/SPAuthPage/saml/metadata


# Keyclock OIDC configuration
spring.security.oauth2.client.registration.employee-portal.client-id=employee-portal
spring.security.oauth2.client.registration.employee-portal.client-secret=C4hX5orzVDcdu1EjzGZfP3NHZkNo5KNP
spring.security.oauth2.client.registration.employee-portal.scope=openid,profile,email
spring.security.oauth2.client.registration.employee-portal.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.employee-portal.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.employee-portal.issuer-uri=http://10.80.241.113:9091/realms/EmployeePortal

# Keyclock SAML Configuration
spring.security.saml2.relyingparty.registration.keycloak.assertingparty.metadata-uri=http://10.80.241.113:9091/realms/EmployeePortal/protocol/saml/descriptor
#spring.security.saml2.relyingparty.registration.keycloak.assertingparty.metadata-uri=classpath:/keyclock-metadat.xml

# KEYCLOAK JWT DIRECT ACCESS GRANT
#keycloak.jwt.token-url=http://10.80.241.113:9091/realms/EmployeePortal/protocol/openid-connect/token
#keycloak.jwt.client-id=Employee_portal
#keycloak.jwt.client-secret=hzQzuAVtiMjcIRdqCxWaE8jgzVT1g8h0

# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:378866511594-qg7vjbrbf4rlk3jt9f5hrth8q2tet54f.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# MICROSOFT SSO
spring.security.oauth2.client.registration.microsoft.client-id=aec19967-b2c9-4159-a936-5548fd394f74
spring.security.oauth2.client.registration.microsoft.client-secret=crl8Q~jHR18LMhP7VdmRg.pQ_VzAkQx9e2YFYasS
spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.redirect-uri={baseUrl}/login/oauth2/code/microsoft
spring.security.oauth2.client.registration.microsoft.client-name=Microsoft
spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/consumers/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/consumers/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-name-attribute=sub

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.mail=DEBUG
#logging.level.org.eclipse.angus.mail=DEBUG
#logging.level.org.springframework.security=TRACE
#server.servlet.session.cookie.same-site=none
#server.servlet.session.cookie.secure=false
#server.servlet.session.cookie.name=JSESSIONID

#logging.level.org.springframework.security.saml2=DEBUG
#logging.level.org.springframework.security.saml2.provider.service.authentication=TRACE
#logging.level.org.opensaml=DEBUG
#logging.level.org.springframework.security.authentication=DEBUG
#logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
#logging.level.org.springframework.security.web.session=DEBUG
#logging.level.org.springframework.security.web.context=DEBUG
#logging.level.org.springframework.security.saml2=TRACE
#logging.level.org.springframework.security.saml2.provider.service=TRACE
#logging.level.org.opensaml=TRACE


