spring.application.name=Registration

server.port=9090

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/
management.endpoints.web.exposure.include=health


spring.datasource.url = jdbc:postgresql://localhost:5432/Registration_Form
spring.datasource.username=postgres
spring.datasource.password=1515
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql = true
spring.jpa.format-sql =true


# OIDC OAuth2 provider configuration
spring.security.oauth2.client.registration.univ.client-id=${UNIV_OAUTH_CLIENT_ID:demo-univ-client}
spring.security.oauth2.client.registration.univ.client-secret=${UNIV_OAUTH_CLIENT_SECRET:demo-univ-secret}
spring.security.oauth2.client.registration.univ.scope=openid,profile,email
spring.security.oauth2.client.registration.univ.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.univ.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.univ.authorization-uri=${UNIV_OAUTH_AUTH_URI:https://example.com/univ/protocol/openid-connect/auth}
spring.security.oauth2.client.provider.univ.token-uri=${UNIV_OAUTH_TOKEN_URI:https://example.com/univ/protocol/openid-connect/token}
spring.security.oauth2.client.provider.univ.jwk-set-uri=${UNIV_OAUTH_JWK_URI:https://example.com/univ/protocol/openid-connect/certs}
spring.security.oauth2.client.provider.univ.user-info-uri=${UNIV_OAUTH_USERINFO_URI:https://example.com/univ/protocol/openid-connect/userinfo}
spring.security.oauth2.client.provider.univ.user-name-attribute=sub

# Keycloak provider configuration
spring.security.oauth2.client.registration.keycloak.client-id=attendance_app
spring.security.oauth2.client.registration.keycloak.client-secret=We2jaqlvqJKg462bad7I1XAprnv4ip08
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:9090/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8180/realms/attendance/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/attendance/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8180/realms/attendance/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:8180/realms/attendance/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.user-name-attribute=sub