spring.application.name=Registration

server.port=9090

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/
management.endpoints.web.exposure.include=health


spring.datasource.url = jdbc:postgresql://localhost:5432/Registration_Form
spring.datasource.username=postgres
spring.datasource.password=1515
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql = true
spring.jpa.format-sql =true